name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/modules-2
          key: gradle-modules-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            gradle-modules-

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-wrapper-

      - name: Build
        run: ./gradlew build

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: plugin/build/reports/tests/test
